// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBm84LXnbVfg9lVS6nuyP-zcpjAi0xsXlo',
    appId: '1:443312016692:web:e5e6f8107a05950dbb2961',
    messagingSenderId: '443312016692',
    projectId: 'myvirtualasistant-ce7ea',
    authDomain: 'myvirtualasistant-ce7ea.firebaseapp.com',
    storageBucket: 'myvirtualasistant-ce7ea.appspot.com',
    measurementId: 'G-0X6F8WCYKM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCe6WN9qzK5bA6z0-BoQdNnsddesJ-D_U4',
    appId: '1:443312016692:android:306cfbb01055303dbb2961',
    messagingSenderId: '443312016692',
    projectId: 'myvirtualasistant-ce7ea',
    storageBucket: 'myvirtualasistant-ce7ea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKHfX7BpqQ0sLxLdXXKk14f8Q-7W-HeqU',
    appId: '1:443312016692:ios:80b01b80f7400533bb2961',
    messagingSenderId: '443312016692',
    projectId: 'myvirtualasistant-ce7ea',
    storageBucket: 'myvirtualasistant-ce7ea.appspot.com',
    iosBundleId: 'com.example.myVirtualAssistant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKHfX7BpqQ0sLxLdXXKk14f8Q-7W-HeqU',
    appId: '1:443312016692:ios:80b01b80f7400533bb2961',
    messagingSenderId: '443312016692',
    projectId: 'myvirtualasistant-ce7ea',
    storageBucket: 'myvirtualasistant-ce7ea.appspot.com',
    iosBundleId: 'com.example.myVirtualAssistant',
  );
}
